---
info:
  description: Training configuration repo

spring:
  profile: cloud

eureka:
  client:
    serviceURL: http://guest:guest@eureka-boisterous-parrot.cfapps.io/eureka
  
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
