---
info:
  description: Training configuration repo

---
spring:
  profiles: cloud

eureka:
  client:
    serviceUrl:
      defaultZone: http://guest:guest@eureka-boisterous-parrot.cfapps.io/eureka

  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
